export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

// Activities
export const START_FOCUS_ACTIVITY = 'START_FOCUS_ACTIVITY';
export const STOP_FOCUS_ACTIVITY = 'STOP_FOCUS_ACTIVITY';
export const START_SLEEP_ACTIVITY = 'START_SLEEP_ACTIVITY';
export const STOP_SLEEP_ACTIVITY = 'STOP_SLEEP_ACTIVITY';

// Saga
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
